name: Ubuntu XFCE RDP

on: [workflow_dispatch]

jobs:
  ubuntu-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Install Desktop & xRDP
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies xrdp
        sudo systemctl enable xrdp
        echo xfce4-session > ~/.xsession
        sudo adduser github --gecos "" --disabled-password
        echo 'github:P@ssw0rd!' | sudo chpasswd
        sudo usermod -aG sudo github
        sudo systemctl restart xrdp

    - name: Install ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update && sudo apt install -y ngrok
        ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        nohup ngrok tcp 3389 &

    - name: Anti-Idle
      run: |
        while true; do echo "Running..."; sleep 60; done
