name: Windows RDP

on: [workflow_dispatch]

jobs:
  desktop:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Download Ngrok
        run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Extract
        run: Expand-Archive ngrok.zip

      - name: Auth Ngrok
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable RDP and firewall
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

      - name: Set runneradmin password
        run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Start RDP Tunnel
        run: Start-Process .\ngrok\ngrok.exe -ArgumentList "tcp 3389"

      - name: Anti-idle
        run: |
          for ($i = 0; $i -lt 720; $i++) {
            Write-Output "Running... $i"
            Start-Sleep -Seconds 30
          }
