name: Ubuntu XFCE RDP (Cloudflared)

on: [workflow_dispatch]

jobs:
  desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Set up XFCE and xRDP
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies xrdp
          sudo systemctl enable xrdp
          sudo adduser ubuntu xrdp
          echo "xfce4-session" > ~/.xsession
          sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config
          sudo systemctl restart xrdp

      - name: Set user password to P@ssw0rd!
        run: echo 'ubuntu:P@ssw0rd!' | sudo chpasswd

      - name: Install and run cloudflared tunnel
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          nohup cloudflared tunnel --url tcp://localhost:3389 > cloudflared.log 2>&1 &

      - name: Anti-idle
        run: |
          while true; do echo "Active..."; sleep 60; done
